server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'python_backend'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'python_backend'
          __path__: /python_backend_logs/backend_*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}[\.,]?\d{0,6})\s+(?P<level_word>\w+)\s+(?P<message>.*)'
      - labels:
          level: level_word
      - timestamp:
          source: time
          format: '%Y-%m-%d %H:%M:%S,%f'
          fallback_formats:
            - '%Y-%m-%d %H:%M:%S.%f'
            - '%Y-%m-%d %H:%M:%S'
      - output:
          source: message

  - job_name: 'migrations'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'migrations'
          __path__: /python_backend_logs/migrations.log

  - job_name: 'mosquitto'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'mosquitto'
          __path__: /python_backend_logs/mosquitto.log

  - job_name: 'node-red'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'node-red'
          __path__: /python_backend_logs/node-red.log

  - job_name: 'zigbee2mqtt'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'zigbee2mqtt'
          __path__: /python_backend_logs/zigbee2mqtt.log